/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 30 14:59:33 GMT 2023
 */

package morriex.entity;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.Set;
import morriex.entity.Comment;
import morriex.entity.Vote;
import morriex.model.CommentModel;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Comment_ESTest extends Comment_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CommentModel commentModel0 = new CommentModel();
      Comment comment0 = new Comment(commentModel0);
      Integer integer0 = Integer.getInteger((String) null, (-1545));
      comment0.addVote(integer0, (String) null);
      Integer integer1 = comment0.getDislikes();
      assertNotNull(integer1);
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CommentModel commentModel0 = new CommentModel();
      Comment comment0 = new Comment(commentModel0);
      comment0.addVote(commentModel0.movieId, "+C.&*QaNibXDzdz,wH");
      assertEquals(1, (int)comment0.getCommentId());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CommentModel commentModel0 = new CommentModel();
      Comment comment0 = new Comment(commentModel0);
      comment0.text = "`<";
      String string0 = comment0.getText();
      assertEquals("`<", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CommentModel commentModel0 = new CommentModel();
      commentModel0.text = "H<-@0q_E9NrN";
      commentModel0.text = "";
      Comment comment0 = new Comment(commentModel0);
      String string0 = comment0.getText();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CommentModel commentModel0 = new CommentModel();
      Comment comment0 = new Comment(commentModel0);
      Integer integer0 = comment0.getLikes();
      commentModel0.movieId = integer0;
      comment0.movieId = null;
      comment0.movieId = null;
      comment0.movieId = commentModel0.movieId;
      Integer integer1 = comment0.getMovieId();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CommentModel commentModel0 = new CommentModel();
      Comment comment0 = new Comment(commentModel0);
      Integer integer0 = comment0.commentId;
      commentModel0.movieId = integer0;
      Comment comment1 = new Comment(commentModel0);
      Integer integer1 = comment1.getMovieId();
      assertEquals(1, (int)integer1);
      assertEquals(2, (int)comment1.getCommentId());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CommentModel commentModel0 = new CommentModel();
      commentModel0.movieId = null;
      Integer integer0 = Integer.getInteger("", (-445));
      commentModel0.movieId = integer0;
      Comment comment0 = new Comment(commentModel0);
      Integer integer1 = comment0.getMovieId();
      assertEquals((-445), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CommentModel commentModel0 = new CommentModel();
      commentModel0.userEmail = "H<-@0q_E9NrN";
      Comment comment0 = new Comment(commentModel0);
      String string0 = comment0.getEmail();
      assertEquals("H<-@0q_E9NrN", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CommentModel commentModel0 = new CommentModel();
      Comment comment0 = new Comment(commentModel0);
      comment0.userEmail = "";
      String string0 = comment0.getEmail();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CommentModel commentModel0 = new CommentModel();
      Comment comment0 = new Comment(commentModel0);
      Integer integer0 = comment0.getLikes();
      comment0.commentId = integer0;
      comment0.getCommentId();
      assertEquals(0, (int)comment0.getCommentId());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CommentModel commentModel0 = new CommentModel();
      Comment comment0 = new Comment(commentModel0);
      comment0.commentId = null;
      Integer integer0 = comment0.getCommentId();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CommentModel commentModel0 = new CommentModel();
      Comment comment0 = new Comment(commentModel0);
      Integer integer0 = Integer.getInteger((String) null, (-1373));
      comment0.commentId = integer0;
      Integer integer1 = comment0.getCommentId();
      assertEquals((-1373), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CommentModel commentModel0 = new CommentModel();
      Comment comment0 = new Comment(commentModel0);
      HashMap<Vote, Vote> hashMap0 = new HashMap<Vote, Vote>();
      Set<Vote> set0 = hashMap0.keySet();
      comment0.votes = set0;
      // Undeclared exception!
      try { 
        comment0.addVote((Integer) null, (String) null);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.AbstractCollection", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CommentModel commentModel0 = new CommentModel();
      Comment comment0 = new Comment(commentModel0);
      comment0.votes = null;
      // Undeclared exception!
      try { 
        comment0.addVote((Integer) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("morriex.entity.Comment", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Comment comment0 = null;
      try {
        comment0 = new Comment((CommentModel) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("morriex.entity.Comment", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CommentModel commentModel0 = new CommentModel();
      Comment comment0 = new Comment(commentModel0);
      Integer integer0 = Integer.getInteger("", (-1));
      comment0.addVote(integer0, (String) null);
      Integer integer1 = comment0.getDislikes();
      assertEquals(1, (int)integer1);
      assertNotNull(integer1);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CommentModel commentModel0 = new CommentModel();
      Comment comment0 = new Comment(commentModel0);
      LinkedHashSet<Vote> linkedHashSet0 = new LinkedHashSet<Vote>();
      comment0.votes = (Set<Vote>) linkedHashSet0;
      Integer integer0 = comment0.getCommentId();
      assertNotNull(integer0);
      
      Vote vote0 = new Vote("0e\"Sk]-b2Q6", integer0);
      linkedHashSet0.add(vote0);
      Integer integer1 = comment0.getDislikes();
      assertEquals(0, (int)integer1);
      assertNotNull(integer1);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CommentModel commentModel0 = new CommentModel();
      Comment comment0 = new Comment(commentModel0);
      LinkedHashSet<Vote> linkedHashSet0 = new LinkedHashSet<Vote>();
      comment0.votes = (Set<Vote>) linkedHashSet0;
      Vote vote0 = new Vote("0e\"Sk]-b2Q6", commentModel0.movieId);
      linkedHashSet0.add(vote0);
      // Undeclared exception!
      try { 
        comment0.getDislikes();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("morriex.entity.Comment", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      CommentModel commentModel0 = new CommentModel();
      Comment comment0 = new Comment(commentModel0);
      Integer integer0 = comment0.commentId;
      assertNotNull(integer0);
      
      comment0.addVote(integer0, (String) null);
      Integer integer1 = comment0.getLikes();
      assertEquals(1, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      CommentModel commentModel0 = new CommentModel();
      Comment comment0 = new Comment(commentModel0);
      Integer integer0 = comment0.getLikes();
      assertNotNull(integer0);
      
      comment0.addVote(integer0, (String) null);
      Integer integer1 = comment0.getLikes();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      CommentModel commentModel0 = new CommentModel();
      Comment comment0 = new Comment(commentModel0);
      String string0 = comment0.getText();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      CommentModel commentModel0 = new CommentModel();
      Comment comment0 = new Comment(commentModel0);
      comment0.addVote(commentModel0.movieId, (String) null);
      // Undeclared exception!
      try { 
        comment0.getLikes();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("morriex.entity.Comment", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      CommentModel commentModel0 = new CommentModel();
      Comment comment0 = new Comment(commentModel0);
      String string0 = comment0.getEmail();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      CommentModel commentModel0 = new CommentModel();
      Comment comment0 = new Comment(commentModel0);
      Integer integer0 = comment0.getMovieId();
      assertNull(integer0);
  }
}
