/*
 * This file was automatically generated by EvoSuite
 * Thu Jul 13 08:16:28 GMT 2023
 */

package morriex.entity;

import org.junit.Test;
import static org.junit.Assert.*;
import morriex.entity.Rating;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Rating_ESTest extends Rating_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer integer0 = new Integer((-3444));
      Rating rating0 = new Rating((String) null, integer0);
      String string0 = rating0.getUserEmail();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Integer integer0 = new Integer((-1925));
      Rating rating0 = new Rating("", integer0);
      rating0.userEmail = "";
      rating0.userEmail = "";
      rating0.userEmail = "";
      rating0.userEmail = "";
      rating0.userEmail = "";
      rating0.userEmail = "BA<P*r04*Cqu^;Ybo7";
      String string0 = rating0.getUserEmail();
      assertEquals("BA<P*r04*Cqu^;Ybo7", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Integer integer0 = new Integer((-1925));
      Rating rating0 = new Rating("", integer0);
      rating0.rate = integer0;
      rating0.rate = integer0;
      Integer integer1 = new Integer(503);
      rating0.rate = integer1;
      Integer integer2 = rating0.getRate();
      assertEquals(503, (int)integer2);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Integer integer0 = new Integer((-3444));
      Rating rating0 = new Rating((String) null, integer0);
      rating0.rate = integer0;
      rating0.rate = integer0;
      rating0.rate = rating0.rate;
      rating0.rate = rating0.rate;
      rating0.rate = rating0.rate;
      rating0.rate = null;
      Integer integer1 = rating0.getRate();
      assertNull(integer1);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Integer integer0 = new Integer((-3444));
      Rating rating0 = new Rating((String) null, integer0);
      Integer integer1 = rating0.getRate();
      assertEquals((-3444), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Rating rating0 = new Rating("B|D{", integer0);
      Integer integer1 = rating0.getRate();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Rating rating0 = new Rating("", (Integer) null);
      String string0 = rating0.getUserEmail();
      assertEquals("", string0);
  }
}
