/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 30 15:04:37 GMT 2023
 */

package morriex.entity;

import org.junit.Test;
import static org.junit.Assert.*;
import morriex.entity.Vote;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Vote_ESTest extends Vote_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Vote vote0 = new Vote("+/}lKR]z8'Uc", (Integer) null);
      vote0.userEmail = "WMgj";
      vote0.userEmail = "";
      vote0.userEmail = "+/}lKR]z8'Uc";
      vote0.userEmail = null;
      String string0 = vote0.getUserEmail();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Integer integer0 = new Integer((-1231));
      Vote vote0 = new Vote("", integer0);
      String string0 = vote0.getUserEmail();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Vote vote0 = new Vote("+/}lKR]z8'Uc", (Integer) null);
      Integer integer0 = new Integer(0);
      vote0.type = integer0;
      Integer integer1 = vote0.getType();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Integer integer0 = new Integer((-4622));
      Vote vote0 = new Vote("/w{VSCP00a", integer0);
      vote0.type = integer0;
      Integer integer1 = new Integer(1);
      vote0.type = integer1;
      Integer integer2 = vote0.getType();
      assertFalse(integer2.equals((Object)integer0));
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Vote vote0 = new Vote("", (Integer) null);
      Integer integer0 = vote0.getType();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Integer integer0 = new Integer((-4622));
      Vote vote0 = new Vote("/w{VSCP00a", integer0);
      String string0 = vote0.getUserEmail();
      assertEquals("/w{VSCP00a", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Integer integer0 = new Integer((-4622));
      Vote vote0 = new Vote("/w{VSCP00a", integer0);
      Integer integer1 = vote0.getType();
      assertEquals((-4622), (int)integer1);
  }
}
