/*
 * This file was automatically generated by EvoSuite
 * Thu Jul 13 08:13:33 GMT 2023
 */

package morriex.entity;

import org.junit.Test;
import static org.junit.Assert.*;
import morriex.entity.Vote;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Vote_ESTest extends Vote_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer integer0 = new Integer((-1));
      Vote vote0 = new Vote("c,)_%oFXnEDDJN", integer0);
      vote0.userEmail = "c,)_%oFXnEDDJN";
      vote0.userEmail = "c,)_%oFXnEDDJN";
      vote0.userEmail = null;
      String string0 = vote0.getUserEmail();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Vote vote0 = new Vote("", integer0);
      Integer integer1 = vote0.getType();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Vote vote0 = new Vote("", integer0);
      vote0.type = integer0;
      vote0.type = integer0;
      vote0.type = integer0;
      vote0.type = vote0.type;
      vote0.type = integer0;
      Integer integer1 = new Integer(1513);
      vote0.type = integer1;
      Integer integer2 = vote0.getType();
      assertEquals(1513, (int)integer2);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Integer integer0 = new Integer((-1));
      Vote vote0 = new Vote("c,)_%oFXnEDDJN", integer0);
      Integer integer1 = vote0.getType();
      assertEquals((-1), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Integer integer0 = new Integer((-1));
      Vote vote0 = new Vote("c,)_%oFXnEDDJN", integer0);
      String string0 = vote0.getUserEmail();
      assertEquals("c,)_%oFXnEDDJN", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Vote vote0 = new Vote("y|-f=6@=q74ulGBk", (Integer) null);
      Integer integer0 = vote0.getType();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Vote vote0 = new Vote("", (Integer) null);
      String string0 = vote0.getUserEmail();
      assertEquals("", string0);
  }
}
