/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 30 15:11:51 GMT 2023
 */

package morriex.commands;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import morriex.commands.AddToWatchList;
import morriex.model.urlParam.AddToWatchListModel;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AddToWatchList_ESTest extends AddToWatchList_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AddToWatchList addToWatchList0 = new AddToWatchList();
      AddToWatchListModel addToWatchListModel0 = new AddToWatchListModel();
      // Undeclared exception!
      try { 
        addToWatchList0.handle(addToWatchListModel0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/gson/TypeAdapterFactory
         //
         verifyException("morriex.commands.AddToWatchList", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AddToWatchList addToWatchList0 = new AddToWatchList();
      AddToWatchListModel addToWatchListModel0 = new AddToWatchListModel();
      // Undeclared exception!
      try { 
        addToWatchList0.handleGet(addToWatchListModel0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/gson/TypeAdapterFactory
         //
         verifyException("morriex.commands.AddToWatchList", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AddToWatchList addToWatchList0 = new AddToWatchList();
      AddToWatchListModel addToWatchListModel0 = new AddToWatchListModel();
      // Undeclared exception!
      try { 
        addToWatchList0.handlePost(addToWatchListModel0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/gson/TypeAdapterFactory
         //
         verifyException("morriex.commands.AddToWatchList", e);
      }
  }
}
