/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 30 15:13:16 GMT 2023
 */

package morriex.commands;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import morriex.commands.GetActorById;
import morriex.model.urlParam.GetActorByIdModel;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class GetActorById_ESTest extends GetActorById_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GetActorById getActorById0 = new GetActorById();
      GetActorByIdModel getActorByIdModel0 = new GetActorByIdModel();
      // Undeclared exception!
      try { 
        getActorById0.handle(getActorByIdModel0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/gson/TypeAdapterFactory
         //
         verifyException("morriex.commands.GetActorById", e);
      }
  }
}
