/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 30 15:16:10 GMT 2023
 */

package morriex.commands;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import morriex.commands.GetMovies;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class GetMovies_ESTest extends GetMovies_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GetMovies getMovies0 = new GetMovies();
      // Undeclared exception!
      try { 
        getMovies0.handle("C QP]]UO", "releaseYear", "releaseYear");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/gson/TypeAdapterFactory
         //
         verifyException("morriex.commands.GetMovies", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GetMovies getMovies0 = new GetMovies();
      // Undeclared exception!
      try { 
        getMovies0.handle("y^S<8@G,epJj11", "y^S<8@G,epJj11", "y^S<8@G,epJj11");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/gson/TypeAdapterFactory
         //
         verifyException("morriex.commands.GetMovies", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GetMovies getMovies0 = new GetMovies();
      // Undeclared exception!
      try { 
        getMovies0.handle("title", "title", "title");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/gson/TypeAdapterFactory
         //
         verifyException("morriex.commands.GetMovies", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      GetMovies getMovies0 = new GetMovies();
      // Undeclared exception!
      try { 
        getMovies0.handle("eH?R6g*LNU70By1\n", (String) null, "eH?R6g*LNU70By1\n");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/gson/TypeAdapterFactory
         //
         verifyException("morriex.commands.GetMovies", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      GetMovies getMovies0 = new GetMovies();
      // Undeclared exception!
      try { 
        getMovies0.handle("genre", "genre", "genre");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/gson/TypeAdapterFactory
         //
         verifyException("morriex.commands.GetMovies", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      GetMovies getMovies0 = new GetMovies();
      // Undeclared exception!
      try { 
        getMovies0.handle((String) null, (String) null, (String) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/gson/TypeAdapterFactory
         //
         verifyException("morriex.commands.GetMovies", e);
      }
  }
}
