/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 30 15:14:32 GMT 2023
 */

package morriex.commands;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import morriex.commands.GetMovieById;
import morriex.model.urlParam.GetMovieByIdModel;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class GetMovieById_ESTest extends GetMovieById_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GetMovieById getMovieById0 = new GetMovieById();
      GetMovieByIdModel getMovieByIdModel0 = new GetMovieByIdModel();
      // Undeclared exception!
      try { 
        getMovieById0.handle(getMovieByIdModel0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/gson/TypeAdapterFactory
         //
         verifyException("morriex.commands.GetMovieById", e);
      }
  }
}
