/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 30 15:17:27 GMT 2023
 */

package morriex.commands;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import morriex.commands.GetMoviesListBySearch;
import morriex.model.urlParam.GetMoviesBySearchModel;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class GetMoviesListBySearch_ESTest extends GetMoviesListBySearch_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GetMoviesListBySearch getMoviesListBySearch0 = new GetMoviesListBySearch();
      GetMoviesBySearchModel getMoviesBySearchModel0 = new GetMoviesBySearchModel();
      // Undeclared exception!
      try { 
        getMoviesListBySearch0.handle(getMoviesBySearchModel0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/gson/TypeAdapterFactory
         //
         verifyException("morriex.commands.GetMoviesListBySearch", e);
      }
  }
}
