/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 30 15:18:06 GMT 2023
 */

package morriex.commands;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import morriex.commands.GetWatchList;
import morriex.model.urlParam.GetWatchListModel;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class GetWatchList_ESTest extends GetWatchList_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GetWatchList getWatchList0 = new GetWatchList();
      GetWatchListModel getWatchListModel0 = new GetWatchListModel();
      // Undeclared exception!
      try { 
        getWatchList0.handle(getWatchListModel0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/gson/TypeAdapterFactory
         //
         verifyException("morriex.commands.GetWatchList", e);
      }
  }
}
