/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 30 15:19:26 GMT 2023
 */

package morriex.commands;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import morriex.commands.RateMovie;
import morriex.model.urlParam.RateModel;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class RateMovie_ESTest extends RateMovie_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RateModel rateModel0 = new RateModel();
      Integer integer0 = Integer.valueOf(184);
      rateModel0.score = integer0;
      RateMovie rateMovie0 = new RateMovie();
      try { 
        rateMovie0.handlePost(rateModel0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // InvalidRateScore
         //
         verifyException("morriex.commands.RateMovie", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RateModel rateModel0 = new RateModel();
      Integer integer0 = Integer.valueOf(2);
      rateModel0.score = integer0;
      RateMovie rateMovie0 = new RateMovie();
      // Undeclared exception!
      try { 
        rateMovie0.handleGet(rateModel0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/gson/TypeAdapterFactory
         //
         verifyException("morriex.commands.RateMovie", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RateMovie rateMovie0 = new RateMovie();
      RateModel rateModel0 = new RateModel();
      try { 
        rateMovie0.handle(rateModel0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("morriex.commands.RateMovie", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RateModel rateModel0 = new RateModel();
      Integer integer0 = Integer.valueOf(130);
      rateModel0.score = integer0;
      RateMovie rateMovie0 = new RateMovie();
      try { 
        rateMovie0.handle(rateModel0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // InvalidRateScore
         //
         verifyException("morriex.commands.RateMovie", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      RateModel rateModel0 = new RateModel();
      Integer integer0 = Integer.valueOf(2);
      rateModel0.score = integer0;
      RateMovie rateMovie0 = new RateMovie();
      // Undeclared exception!
      try { 
        rateMovie0.handle(rateModel0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/gson/TypeAdapterFactory
         //
         verifyException("morriex.commands.RateMovie", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      RateModel rateModel0 = new RateModel();
      Integer integer0 = Integer.valueOf(10);
      rateModel0.score = integer0;
      RateMovie rateMovie0 = new RateMovie();
      // Undeclared exception!
      try { 
        rateMovie0.handlePost(rateModel0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/gson/TypeAdapterFactory
         //
         verifyException("morriex.commands.RateMovie", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      RateModel rateModel0 = new RateModel();
      Integer integer0 = Integer.valueOf(170);
      rateModel0.score = integer0;
      RateMovie rateMovie0 = new RateMovie();
      try { 
        rateMovie0.handleGet(rateModel0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // InvalidRateScore
         //
         verifyException("morriex.commands.RateMovie", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      RateModel rateModel0 = new RateModel();
      RateMovie rateMovie0 = new RateMovie();
      try { 
        rateMovie0.handleGet(rateModel0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("morriex.commands.RateMovie", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      RateModel rateModel0 = new RateModel();
      RateMovie rateMovie0 = new RateMovie();
      try { 
        rateMovie0.handlePost(rateModel0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("morriex.commands.RateMovie", e);
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      RateMovie rateMovie0 = new RateMovie();
      RateModel rateModel0 = new RateModel();
      Integer integer0 = Integer.valueOf(0);
      rateModel0.score = integer0;
      try { 
        rateMovie0.handle(rateModel0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // InvalidRateScore
         //
         verifyException("morriex.commands.RateMovie", e);
      }
  }
}
