/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 30 15:20:20 GMT 2023
 */

package morriex.commands;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import morriex.commands.RemoveFromWatchList;
import morriex.model.urlParam.RemoveFromWatchListModel;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class RemoveFromWatchList_ESTest extends RemoveFromWatchList_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RemoveFromWatchList removeFromWatchList0 = new RemoveFromWatchList();
      // Undeclared exception!
      try { 
        removeFromWatchList0.handle((RemoveFromWatchListModel) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/gson/TypeAdapterFactory
         //
         verifyException("morriex.commands.RemoveFromWatchList", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RemoveFromWatchList removeFromWatchList0 = new RemoveFromWatchList();
      RemoveFromWatchListModel removeFromWatchListModel0 = new RemoveFromWatchListModel();
      // Undeclared exception!
      try { 
        removeFromWatchList0.handlePost(removeFromWatchListModel0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/gson/TypeAdapterFactory
         //
         verifyException("morriex.commands.RemoveFromWatchList", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RemoveFromWatchList removeFromWatchList0 = new RemoveFromWatchList();
      // Undeclared exception!
      try { 
        removeFromWatchList0.handleGet((RemoveFromWatchListModel) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/gson/TypeAdapterFactory
         //
         verifyException("morriex.commands.RemoveFromWatchList", e);
      }
  }
}
