/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 30 15:21:09 GMT 2023
 */

package morriex.commands;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import morriex.commands.SearchMoviesByReleaseDate;
import morriex.model.urlParam.SearchMovieByReleaseDateModel;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SearchMoviesByReleaseDate_ESTest extends SearchMoviesByReleaseDate_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SearchMoviesByReleaseDate searchMoviesByReleaseDate0 = new SearchMoviesByReleaseDate();
      try { 
        searchMoviesByReleaseDate0.handle((SearchMovieByReleaseDateModel) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("morriex.commands.SearchMoviesByReleaseDate", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SearchMoviesByReleaseDate searchMoviesByReleaseDate0 = new SearchMoviesByReleaseDate();
      SearchMovieByReleaseDateModel searchMovieByReleaseDateModel0 = new SearchMovieByReleaseDateModel();
      Integer integer0 = Integer.getInteger("DTSXhi[CX+", (-1581));
      searchMovieByReleaseDateModel0.endYear = integer0;
      searchMovieByReleaseDateModel0.startYear = integer0;
      // Undeclared exception!
      try { 
        searchMoviesByReleaseDate0.handle(searchMovieByReleaseDateModel0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/gson/TypeAdapterFactory
         //
         verifyException("morriex.commands.SearchMoviesByReleaseDate", e);
      }
  }
}
