/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 30 15:21:47 GMT 2023
 */

package morriex.commands;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import morriex.commands.SortMovies;
import morriex.model.urlParam.SortMoviesModel;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SortMovies_ESTest extends SortMovies_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SortMovies sortMovies0 = new SortMovies();
      SortMoviesModel sortMoviesModel0 = new SortMoviesModel();
      // Undeclared exception!
      try { 
        sortMovies0.handle(sortMoviesModel0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/gson/TypeAdapterFactory
         //
         verifyException("morriex.commands.SortMovies", e);
      }
  }
}
