/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 30 15:23:02 GMT 2023
 */

package morriex.commands;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import morriex.commands.VoteComment;
import morriex.model.urlParam.VoteCommentModel;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class VoteComment_ESTest extends VoteComment_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      VoteComment voteComment0 = new VoteComment();
      try { 
        voteComment0.handlePost((VoteCommentModel) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("morriex.commands.VoteComment", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      VoteComment voteComment0 = new VoteComment();
      VoteCommentModel voteCommentModel0 = new VoteCommentModel();
      Integer integer0 = Integer.getInteger((String) null, (-1));
      voteCommentModel0.vote = integer0;
      // Undeclared exception!
      try { 
        voteComment0.handlePost(voteCommentModel0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/gson/TypeAdapterFactory
         //
         verifyException("morriex.commands.VoteComment", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      VoteComment voteComment0 = new VoteComment();
      try { 
        voteComment0.handleGet((VoteCommentModel) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("morriex.commands.VoteComment", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      VoteComment voteComment0 = new VoteComment();
      try { 
        voteComment0.handle((VoteCommentModel) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("morriex.commands.VoteComment", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      VoteComment voteComment0 = new VoteComment();
      VoteCommentModel voteCommentModel0 = new VoteCommentModel();
      try { 
        voteComment0.handle(voteCommentModel0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // InvalidVoteValue
         //
         verifyException("morriex.commands.VoteComment", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      VoteComment voteComment0 = new VoteComment();
      VoteCommentModel voteCommentModel0 = new VoteCommentModel();
      Integer integer0 = Integer.getInteger((String) null, (-1));
      voteCommentModel0.vote = integer0;
      // Undeclared exception!
      try { 
        voteComment0.handle(voteCommentModel0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/gson/TypeAdapterFactory
         //
         verifyException("morriex.commands.VoteComment", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      VoteComment voteComment0 = new VoteComment();
      VoteCommentModel voteCommentModel0 = new VoteCommentModel();
      Integer integer0 = Integer.getInteger((String) null, (-1));
      voteCommentModel0.vote = integer0;
      // Undeclared exception!
      try { 
        voteComment0.handleGet(voteCommentModel0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/gson/TypeAdapterFactory
         //
         verifyException("morriex.commands.VoteComment", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      VoteComment voteComment0 = new VoteComment();
      VoteCommentModel voteCommentModel0 = new VoteCommentModel();
      try { 
        voteComment0.handlePost(voteCommentModel0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // InvalidVoteValue
         //
         verifyException("morriex.commands.VoteComment", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      VoteComment voteComment0 = new VoteComment();
      VoteCommentModel voteCommentModel0 = new VoteCommentModel();
      try { 
        voteComment0.handleGet(voteCommentModel0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // InvalidVoteValue
         //
         verifyException("morriex.commands.VoteComment", e);
      }
  }
}
