/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 30 15:05:15 GMT 2023
 */

package morriex.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import morriex.exception.ActorNotFound;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ActorNotFound_ESTest extends ActorNotFound_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ActorNotFound actorNotFound0 = new ActorNotFound();
      String string0 = actorNotFound0.getMessage();
      assertEquals("ActorNotFound", string0);
      assertEquals(404, (int)actorNotFound0.getStatus());
  }
}
