/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 30 15:05:54 GMT 2023
 */

package morriex.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import morriex.exception.AgeLimitError;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AgeLimitError_ESTest extends AgeLimitError_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AgeLimitError ageLimitError0 = new AgeLimitError();
      String string0 = ageLimitError0.getMessage();
      assertEquals(403, (int)ageLimitError0.getStatus());
      assertEquals("AgeLimitError", string0);
  }
}
