/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 30 15:06:32 GMT 2023
 */

package morriex.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import morriex.exception.CommentNotFound;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CommentNotFound_ESTest extends CommentNotFound_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CommentNotFound commentNotFound0 = new CommentNotFound();
      String string0 = commentNotFound0.getMessage();
      assertEquals("CommentNotFound", string0);
      assertEquals(404, (int)commentNotFound0.getStatus());
  }
}
