/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 30 15:08:24 GMT 2023
 */

package morriex.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import morriex.exception.InvalidRateScore;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class InvalidRateScore_ESTest extends InvalidRateScore_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      InvalidRateScore invalidRateScore0 = new InvalidRateScore();
      String string0 = invalidRateScore0.getMessage();
      assertEquals(403, (int)invalidRateScore0.getStatus());
      assertEquals("InvalidRateScore", string0);
  }
}
