/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 30 15:10:19 GMT 2023
 */

package morriex.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import morriex.exception.MovieNotFound;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MovieNotFound_ESTest extends MovieNotFound_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MovieNotFound movieNotFound0 = new MovieNotFound();
      String string0 = movieNotFound0.getMessage();
      assertEquals(404, (int)movieNotFound0.getStatus());
      assertEquals("MovieNotFound", string0);
  }
}
