/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 30 15:09:41 GMT 2023
 */

package morriex.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import morriex.exception.MovieAlreadyExists;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MovieAlreadyExists_ESTest extends MovieAlreadyExists_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MovieAlreadyExists movieAlreadyExists0 = new MovieAlreadyExists();
      String string0 = movieAlreadyExists0.getMessage();
      assertEquals(403, (int)movieAlreadyExists0.getStatus());
      assertEquals("MovieAlreadyExists", string0);
  }
}
