/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 30 15:10:58 GMT 2023
 */

package morriex.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import morriex.exception.UserNotFound;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UserNotFound_ESTest extends UserNotFound_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UserNotFound userNotFound0 = new UserNotFound();
      String string0 = userNotFound0.getMessage();
      assertEquals(404, (int)userNotFound0.getStatus());
      assertEquals("UserNotFound", string0);
  }
}
