/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 30 10:17:35 GMT 2023
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.ComplexProgram;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ComplexProgram_ESTest extends ComplexProgram_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      boolean boolean0 = ComplexProgram.isPrime(9);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      boolean boolean0 = ComplexProgram.isPrime(2);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = ComplexProgram.sumDigits(0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = ComplexProgram.sumDigits((-9));
      assertEquals((-9), int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      // Undeclared exception!
      ComplexProgram.isPrime(341382539);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      int int0 = ComplexProgram.sumDigits(4122);
      assertEquals(9, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      boolean boolean0 = ComplexProgram.isPrime(0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ComplexProgram complexProgram0 = new ComplexProgram();
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      String[] stringArray0 = new String[2];
      ComplexProgram.main(stringArray0);
      assertEquals(2, stringArray0.length);
  }
}
